### ISSUE TITLE
General requirements.txt while using Per-function requirements

### ISSUE THREAD

**Issue by amitm02** [serverless/serverless-python-requirements#174]
Can i keep a general requirements.txt file in the root folder for all general functions and an additional unique requirements.txt for a specific function in a module folder?
e.g

├── serverless.yml
├── requirements.txt
├── functions.py
├── specialFunctionWithAdditionalRequirments
│      ├── requirements.txt 
│      └── specialFunction.py

```
package:
  individually: true

functions:
  func1:
    handler:  functions.func1
  func2:
    handler:  functions.func2
 special:
    handler: specialFunction.handler
    module: specialFunctionWithAdditionalRequirments
```

attempting to do "sls deploy -f func1" in this configuration resulted me in:
```
Cannot read property 'artifact' of undefined error
TypeError: Cannot read property 'artifact' of undefined
    at values.forEach (.../node_modules/serverless-python-requirements/lib/inject.js:113:21)
    at Array.forEach (<anonymous>)
    at ServerlessPythonRequirements.injectAllRequirements (.../node_modules/serverless-python-requirements/lib/inject.js:99:8)
```

Edit: there is an high chance that the error (bug) is more general to 4.0.0 and unrelated to the per-function feature, as it happens to me also after reverting back to one requirement.txt file
