### ISSUE TITLE
Feature request: Add pre/post command for docker build

### ISSUE THREAD

**Issue by rokoroku** [serverless/serverless-python-requirements#225]
In case of a dependency that requires native binaries before `pip install` command,
so currently I'm handling it like this way:
```yml
    pythonBin: >-
      curl --silent -L https://example.com/source.tar.gz | tar xzf &&
      docker run -v "$(pwd):/var/task:z" -u 0 sls-py-reqs-custom ./source/make install &&
      docker run -v "$(pwd):/var/task:z" -u 0 sls-py-reqs-custom python3
    pipCmdExtraArgs:
      - && docker run --rm -v "$(pwd):/var/task:z" -u 0 cp -R /build .serverless/requirements   
```

but if we have something like preDockerCmd / postDockerCmd, we can achieve it like this way:
```yml
    preDockerCmd:
      - curl --silent -L https://example.com/source.tar.gz | tar xzf
      - ./source/make install

    postDockerCmd:
      - cp -R /build .serverless/requirements   
```

reference:

https://stackoverflow.com/a/26274399/2305379

**Comment by dschep** [comment]
Not a bad idea. For situations like yours where you seem to be ok with separate `docker run` invocations, it might make sense to add have the plugin fire off custom [lifecycle events](https://gist.github.com/HyperBrain/50d38027a8f57778d5b0f135d80ea406) which can then be more easily tapped into with plugins like [serverless-plugin-scripts](https://github.com/mvila/serverless-plugin-scripts).

then you could (with that plugin) do something like this:
```yaml
custom:
  scripts:
    hooks:
      'before:requirements:pip:install': curl --silent -L https://example.com/source.tar.gz | tar xzf && docker run -v "$(pwd):/var/task:z" -u 0 sls-py-reqs-custom ./source/make install
      'after:requirements:pip:install': cp -R /build .serverless/requirements
```

**Comment by rokoroku** [comment]
@dschep Yeah but things like `sls-py-reqs-custom` and `.serverless/requirements` is kind of a hack into  `serverless-python-requirements`'s internal (which means they might be highly likely changed without any announcement.)

So it's better to have that hooks with `custom.pythonRequirements` variable. 
I think it can be applied to both docker / without docker environment

e.g.

```yml
custom:
  pythonRequirements:
    # hooks can be applied to both environment with/without docker
    hooks:
       # accepting both string or string array 
      'before:requirements:pip:install': ...
      'after:requirements:pip:install': 
         - ...
         - ...

```
