### ISSUE TITLE
AWS Layers: Unresolved resource dependencies [PythonRequirementsLambdaLayer]

### ISSUE THREAD

**Issue by luisdemarchi** [serverless/serverless-python-requirements#328]
I'm trying to use AWS Layers, but by the size of each lambda function packet you can realize that all third-party libraries (from the requirements.txt files) were packed together.

At the end of each process, I'm getting this error:

> The CloudFormation template is invalid: Error in template format: unresolved resource dependencies [PythonRequirementsLambdaLayer] in template Features block

My serverless.yml:
```
custom:
  ...
  pythonRequirements:
    layer: true

package:
  individually: true
  exclude:
    - ./**

function1:
  module: module/channels
  handler: f1/hook.received_data
  vendor: ./common
  package:
    include:
      - module/channels/f1/hook.py
  layers:
    - {Ref: PythonRequirementsLambdaLayer}

function2:
  module: module/users
  handler: f2/singup.sing_up
  memorySize: 128
  vendor: ./common
  package:
    include:
      - module/channels/f2/hook.py
  layers:
    - {Ref: PythonRequirementsLambdaLayer}
```
