### ISSUE TITLE
individual packaging results in ENOENT

### ISSUE THREAD

**Issue by felschr** [serverless/serverless-python-requirements#397]
I was getting the following error after setting up serverless-python-requirements for my project:
```
Error: ENOENT: no such file or directory, open 'C:\Users\felix_schroeter\Documents\Projects\projectname\.serverless\src\stepfunction\4_findDate-projectname-staging-extractDate.zip'
```

I'm using `package: individually: true` with the following `pythonRequirements` config:
```yaml
  pythonRequirements:
    dockerizePip: false
```

And here is my function:
```yaml
  extractDate:
    module: src/stepfunction/4_findDate
    handler: lambda_date.lambda_handler
    runtime: python2.7
    package:
      include:
        - src/stepfunction/4_findDate/**
```

After looking into the matter a bit I found a solution. I removed the module part of the following line:
https://github.com/UnitedIncome/serverless-python-requirements/blob/c9d910cc40d95163f8894abfdefaf9c4fc33b505/lib/inject.js#L106
so it just becomes:
```
`${func.name}.zip`
```

Afterwards the deployment ran without an error. I guess it's because my function's `module` part is more than 1 folder deep?
I'm not sure if the python dependencies were properly injected into the packages, though. But that might be another issue.
