### ISSUE TITLE
Support for custom Pipfile location

### ISSUE THREAD

**Issue by danielbayerlein** [serverless/serverless-python-requirements#404]
Does the plugin currently support an alternative path for the `Pipfile`? My folder structure looks like this:

```
.
├── backend
│   ├── Pipfile
│   ├── Pipfile.lock
├── client
│   └── package.json
├── serverless.yml
```

However, the `Pipfile` is expected in the root directory. The following option would be helpful:

```
custom:
  pythonRequirements:
    pipenv:
        file: backend/Pipenv
```
