### ISSUE TITLE
AWS lambda, cannot import name 'etree' from 'lxml' 

### ISSUE THREAD

**Issue by hrabkin** [serverless/serverless-python-requirements#432]
After uploading and running lambda function I receive the following error:
```
{
  "errorMessage": "cannot import name 'etree' from 'lxml'
 (/var/task/lxml/__init__.py)",
  "errorType": "ImportError",
  "stackTrace": [

```
My `serverless.yml` has the following settings applied:
```
custom:
  pythonRequirements:
    dockerizePip: true
    dockerFile: Dockerfile

plugins:
  - serverless-python-requirements
```

I have lxml installed in my `venv` (`requirements.txt` file)

I tried to check package using `sls package -> zipinfo` commands and I see that `lxml` on board
I work under OS-X environment

Any help with this?
