### ISSUE TITLE
serverless docker images (python 3.9)

### ISSUE THREAD

**Issue by gmetzker** [serverless/serverless-python-requirements#647]
I'm wondering if you have considered publishing your own set of python docker images for use in your plugin?  Lambci lacks support for python 3.9, despite a [PR](https://github.com/lambci/docker-lambda/pull/348) and several [requests](https://github.com/lambci/docker-lambda/issues/343).  Others are wondering [what the status of the project is](https://github.com/lambci/docker-lambda/issues/353).  It seems they have not updated their other docker images in 10 months or so.

It would be super helpful to have a verified set of images on docker hub from a trusted source.

**Comment by ronkorving** [comment]
If it helps, I switched to `mlupin/docker-lambda:python3.9-build`

**Comment by sscarduzio** [comment]
how do you "switch" to another image? All I am doing is sls deploy, and it looks for lamci's non-existing 3.9 build image. Where do I specify the docker image for building?

**Comment by ronkorving** [comment]
@sscarduzio :

```yaml
custom:
  pythonRequirements:
    dockerImage: mlupin/docker-lambda:python3.9-build
```

**Comment by mhihasan** [comment]
But, we need some kind of "official" support for those docker images of new python versions.

**Comment by yusukegoto** [comment]
PR hasn't been merged.
https://github.com/lambci/docker-lambda/pull/348

**Comment by takeda** [comment]
@mhihasan despite repo's name it's not some kind of official Amazon AWS repo. Just somebody who created docker images that replicate AWS lambda environment. mlupin/docker-lambda is as official as this one is.

This repo was not touched over a year even though owner appears to contribute to other of his repos. I think we are told to move on and he is not interested in maintaining it.

**Comment by bryantbiggs** [comment]
can we just switch to SAM CLI build images? They will always have support https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-image-repositories.html

**Comment by jcranendonk** [comment]
I've been successful using `dockerImage: public.ecr.aws/sam/emulation-python3.9:latest`.

**Comment by zhemaituk** [comment]
Good stuff, but there are some downsides though, comparing to mlupin images. E.g. when `pip install psutil` on AWS image:
`error: command 'gcc' failed: No such file or directory`

**Comment by tooruuetani** [comment]
How about `public.ecr.aws/sam/build-python3.9` ?
It works for me.

**Comment by zhemaituk** [comment]
@tooruuetani thank you, works like a charm.

My config for aarch64 build:
```
provider:
  name: aws
  runtime: python3.9
  architecture: arm64
custom:
  pythonRequirements:
    slim: true
    dockerizePip: true
    dockerRunCmdExtraArgs: [ '--platform', 'linux/arm64/v8' ]
    dockerImage: public.ecr.aws/sam/build-python3.9:latest-arm64
```
