### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by lencshu** [serverless/serverless-python-requirements#659]
"cannot import name 'DBManager' from 'DBManager' (/opt/python/DBManager/__init__.py)"

No matter how I change the yml, the err still exists, but openpyxl works well, any ideas?

here is part of my code:

serverless.yml
```yml
provider:
  name: aws
  runtime: python3.9
  stage: v15
  region: eu-west-3
  endpointType: REGIONAL

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    layer: true
```

requirements.txt
```
bcrypt==3.2.0
cffi==1.15.0
click==8.0.3
colorama==0.4.4
DBManager==0.1.3
et-xmlfile==1.1.0
mypy-extensions==0.4.3
openpyxl==3.0.9
paramiko==2.8.1
pathspec==0.9.0
platformdirs==2.4.0
pycparser==2.21
PyNaCl==1.4.0
pysftp==0.2.9
regex==2021.11.10
six==1.16.0
tomli==1.2.2
typing_extensions==4.0.0
```

python code
```
from DBManager import DBManager
```

Thx in advance,
