### ISSUE TITLE
zip: true and layer: true puts requirements zip in both layer and lambda

### ISSUE THREAD

**Issue by m-radzikowski** [serverless/serverless-python-requirements#661]
With configuration:

```
custom:
  pythonRequirements:
    dockerizePip: non-linux
    zip: true
    layer: true
```

there are two output zip files - one for Lambda, other for Layer.

The plugin seems to first create `./.requirements.zip` file with all the requirements, then put the content into `./.serverless/pythonRequirements.zip`. Then it generates zip for Lambda function code taking everything from the stack directory and putting it into `./.serverless/fn-name.zip`. It includes the `.requirements.zip` file.

Related: #365
