### ISSUE TITLE
Problem installing native sftp

### ISSUE THREAD

**Issue by shaunc** [serverless/serverless-python-requirements#671]
I am trying to add sftp to the image and call it using `subprocess.call()` to get around a paramiko bug involving jumphosts.

Following [the documentation](https://github.com/serverless/serverless-python-requirements#native-code-dependencies-during-runtime), I add to a custom dockerfile:
```Dockerfile
FROM lambci/lambda:build-python3.8 as base

RUN yum install -y libffi libffi-devel openssh openssh-clients
```
Then configure to add to runtime package:
```yaml
    dockerFile: ./Dockerfile
    dockerExtraFiles:
    - /usr/bin/sftp
    - /lib64/libcrypto.so.10
    - /lib64/libgssapi_krb5.so.2
    - /lib64/libk5crypto.so.3
    - /lib64/libkeyutils.so.1
    - /lib64/libkeyutils.so.1
    - /lib64/libkrb5.so.3
    - /lib64/libkrb5support.so.0
    - /lib64/libssl.so.10
    - /lib64/libssl3.so
    - /libcrypto.so.10
```
and add to package:
```yaml
package:
  patterns:
    - '!.serverless*/**'
    - '!node_modules/**'
    - '/usr/bin/sftp'
    - '/lib64/**'
```
However,  when I look in the image, I see sftp executable, but no lib64 dependencies:
```shell
$ zipinfo .serverless/cdh-send-sftp-frb.zip | grep usr/bin/sftp
-rwxr-xr-x  3.0 unx   129544 b- defN 80-Jan-01 00:00 usr/bin/sftp
```
```shell
$ zipinfo .serverless/cdh-send-sftp-frb.zip | grep usr/bin/sftp
-rwxr-xr-x  3.0 unx   129544 b- defN 80-Jan-01 00:00 usr/bin/sftp
```
```shell
(base) shauncutts@silk:~/.../cdh-send-sftp-frb$ zipinfo .serverless/cdh-send-sftp-frb.zip | grep lib64
-rwxr-xr-x  3.0 unx   216192 b- defN 80-Jan-01 00:00 lib64/ld-linux-x86-64.so.2
```
(well, almost no .. not the ones I asked for!)

As a result, sftp doesn't run. How can I get the files I need from the docker image?
