### ISSUE TITLE
retain option not valid

### ISSUE THREAD

**Issue by dmtzs** [serverless/serverless-python-requirements#697]
When I try to create a layer with the retain option in true the plugin doesnt allow me to do my deploy, is this is going to be fixed?
My fragment of that part is like below:
```yml
custom:
  pythonRequirements:
    layer:
      name: layerserverlesstest
      description: Only a test to create a layer
      compatibleRuntimes:
        - python3.7
      compatibleArchitectures:
        - x86_64
      retain: true
```
