### ISSUE TITLE
Original error was: No module named 'numpy.core._multiarray_umath' when using Numpy

### ISSUE THREAD

**Issue by Bakhtiyar-Garashov** [serverless/serverless-python-requirements#698]
Hello. I am using the plugin to install pandas and numpy. But still get `Original error was: No module named 'numpy.core._multiarray_umath' error`

Device : MacOs x Monterey 12.3.1 
Python runtime: 3.9

```
bakhtiyar@Bakhtiyars-MacBook-Pro one_com % serverless -v                                                                                            
Running "serverless" from node_modules
Framework Core: 3.3.0 (local) 3.0.1 (global)
Plugin: 6.1.0
SDK: 4.3.1
```

Would appreciate any help. 

Note: I can fix the problem by manually building and updating .zip file as a layer. Please, don't recommend that way :)

Note 2: My config yaml file

```
plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    fileName: ../requirements-serverless.txt
    dockerizePi: non-linux
    layer: true
    slim: true # otherwise slimPatterns will not work
    strip: false # avoid some ELF alignment issues
    slimPatternsAppendDefaults: false
    slimPatterns:
      - '**/*.py[c|o]'
      - '**/__pycache__*'
```

**Comment by TinoOnline** [comment]
I have a similar issue, did you end up finding a solution to the problem?

**Comment by pgrzesik** [comment]
Hey there, I think the problem here is a mismatch between the architecture on which you're building the project (arm64) and the one used by AWS Lambda (x86_64). I wrote a blog post about it: https://pgrzesik.com/posts/making-numpy-serverless/, but if you want a tldr:

```
custom:
  pythonRequirements:
    dockerizePip: true
    dockerImage: public.ecr.aws/sam/build-python3.8:latest-x86_64
```

should do the trick, replace `x86_64` with `arm64` if your function is configured for that architecture and use python3.9 image if you're using that version of runtime. I'm going to close the issue.
