### ISSUE TITLE
GitLab CI : [Errno 2] No such file or directory: '/var/task/requirements.txt

### ISSUE THREAD

**Issue by newza-fullmetal** [serverless/serverless-python-requirements#706]
I would like to use this plugin in a CI in gitlab. 
I own a gitlab Runner with rights to use docker in order do avoid docker:dind service (same error anyway on shared runners) 

My image is a node-alpine so it is a **linux** platform. And the build fail during the dockerization with the lambci/lambda:build-python3.8. For an unknown reason I have an 

```
Serverless: Running docker run --rm -v /builds/nanocloud/data-analysis/nanobis/.serverless/requirements\:/var/task\:z lambci/lambda\:build-python3.8 /bin/sh -c 'python3.8 -m pip install -t /var/task/ -r /var/task/requirements.txt && chown -R 0\\:0 /var/task && find /var/task -name \\*.so -exec strip \\{\\} \\;'...
Serverless: Stdout: 
Serverless: Stderr: ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/var/task/requirements.txt'
 ```
 
 The requirement file is not found but it works perfectly fine in local on mac OS. (darwin so non-linux) 
 
 here the serverless config part : 
 ```
 custom:
  pythonRequirements:
    dockerizePip: true # Compiling non-pure-Python modules
    # zip: true # useless with layer (already a zip)
    useDownloadCache: false # enabled by default
    useStaticCache: false # enabled by default
    # invalidateCaches: true # only usefull if we use our own python lib
    layer: true # share the requirement between all functions
    slim: true # This will: strip the .so files, remove __pycache__ and dist-info directories as well as .pyc and .pyo files. 
    slimPatterns: # To add our own file pattern to slim
      - '**/tests/'    
```
 
 the gitlab CI :
 ```
 image: node:lts-alpine # need real debian to get some necessary tool for python compilation and also python & node 
# image: nikolaik/python-nodejs:python3.8-nodejs16-bullseye # need real debian to get some necessary tool for python compilation and also python & node 

stages:
  - build
  - deploy

before_script:
  - mkdir -p ~/.aws/
  - echo $AWS_CREDENTIALS | base64 -d > ~/.aws/credentials
  - echo $AWS_CONFIG | base64 -d > ~/.aws/config
  - echo $AWS_CONFIG | base64 -d 
  - export AWS_SDK_LOAD_CONFIG=1 

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .npm/
    - node_modules/

publish:
  stage: build
  script:
    - npm ci
  only:
    - master
    - tags
    
deploy_dev:
  stage: deploy
  variables:
    ENV: dev
  script:
    - apk add --no-cache docker docker-cli
    - docker info
    - AWS_PROFILE=TOTO ./node_modules/.bin/serverless deploy -s $ENV
  only:
    - master
 ```
 
 I have been able to deploy successfully by disabling dockerizePip and building locally (with the commented image on the ci)  but we lose an important ability of the plugin because it is not same env of a lambda.
 
 Furthermore I have noticed someting weird in the file index.js of the lib. 
 if we declare 'non-linux' for dockerizePip but we really are it deactivate the function. If we are on darwin it  is still activated for exemple. 
  l.65 - 67 
 ```
     if (options.dockerizePip === 'non-linux') {
      options.dockerizePip = process.platform !== 'linux';
    }
    ```
