### ISSUE TITLE
pipenv lock --keep-outdated Exited with code 2

### ISSUE THREAD

**Issue by gmetzker** [serverless/serverless-python-requirements#754]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Are you using the latest plugin release?

- [X] Yes, I'm using the latest plugin release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

After upgrading `serverless-python-requirements` from version `5.4.0` to `6.0.0` serverless fails during deploy.

I can't seem to reproduce the issue locally, this error happens in a build agent.

```
 × Stack XXXXXX failed to deploy (1s)
 25hEnvironment: linux, node 14.20.1, framework 3.22.0 (local), plugin 6.2.2, SDK 4.3.2
Credentials: Local, environment variables
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Error: `pipenv lock --keep-outdated` Exited with code 2
    at ChildProcess.<anonymous> (/tmp/build/31b3a43a/serverless-project/node_modules/child-process-ext/spawn.js:38:8)
    at ChildProcess.emit (events.js:400:28)
    at ChildProcess.emit (domain.js:475:12)
    at maybeClose (internal/child_process.js:1088:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)

1 deprecation found: run 'serverless doctor' for more details

```

Relevant versions:

- serverless-python-requirements: 6.0.0
- pipenv (tried multiple versions all have the same issue: 2022.12.19, 2022.11.5, 2021.11.23)
-serverless 3.22.0
-pip 22.3.1
- node: v14.20.1
- npm: 6.14.17

In my Pipfile, I have the primary source pointed to a private nexus url.  
```
[[source]]
url = "https://{private_nexus_url}/repository/pypi-all/simple"
verify_ssl = true
name = "nexus"

[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"
```

Do you have any suggestions on what may be happening or extra debug steps I can perform/enable?

### Service configuration (serverless.yml) content

```yaml
plugins:
  - serverless-python-requirements
  - serverless-plugin-stage-variables
  - serverless-binary-cors

custom:
    pythonRequirements:

      dockerizePip: true

      slim: true
      slimPatterns:
         # remove the "**/*.egg-info/*" and "**/tests/*" in dependency packages
         - '**/*.egg-info/*'
         - '**/tests/*'
      usePipenv: true
      pipCmdExtraArgs:
         - --extra-index-url
         - https://{private_nexus_url}/repository/pypi-all/simple
      noDeploy: []
```

### Command name and used flags

serverless deploy

### Command output

```shell
Packaging
2Generating requirements.txt from Pipfile

 × Stack XXXXXXX failed to deploy (1s)
 25hEnvironment: linux, node 14.20.1, framework 3.22.0 (local), plugin 6.2.2, SDK 4.3.2
Credentials: Local, environment variables
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Error: `pipenv lock --keep-outdated` Exited with code 2
    at ChildProcess.<anonymous> (/tmp/build/31b3a43a/serverless-project/node_modules/child-process-ext/spawn.js:38:8)
    at ChildProcess.emit (events.js:400:28)
    at ChildProcess.emit (domain.js:475:12)
    at maybeClose (internal/child_process.js:1088:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)

1 deprecation found: run 'serverless doctor' for more details
Terminating Docker daemon.
Waiting for Docker daemon to exit...
Docker exited after 1 seconds.
```

### Environment information

```shell
Framework Core: 3.22.0 (local)
Plugin: 6.2.2
SDK: 4.3.2

Other plugins:
{
  "dependencies": {
    "serverless": "^3.22.0",
    "serverless-binary-cors": "0.0.1",
    "serverless-plugin-stage-variables": "^1.10.1",
    "serverless-python-requirements": "^6.0.0"
  }
}
```
