### ISSUE TITLE
Installing required Python packages step hangs

### ISSUE THREAD

**Issue by cdimitroulas** [serverless/serverless-python-requirements#95]
Hi there,

Not sure why or how this happened but now when I run `sls deploy` the command hangs on the
`Installing required Python packages with python3.6...` step.

I tried reverting back to a commit where I know the project was working because I deploy it yesterday and I am still having this issue so this makes me think this has nothing to do with the changes I made (which is weird).

Any help would be much appreciated.

I am using serverless-python-requirements v3.0.7 and this is my serverless.yml (before the changes):
```yaml
service: calculate-match-score                                                                                                                                                                                     
                                                                                                                                                                                                                   
provider:                                                                                                                                                                                                          
  name: aws                                                                                                                                                                                                        
  runtime: python3.6                                                                                                                                                                                               
  stage: dev                                                                                                                                                                                                       
  region: eu-west-1                                                                                                                                                                                                
  timeout: 180                                                                                                                                                                                                     
  iamRoleStatements:                                                                                                                                                                                               
    - Effect: Allow                                                                                                                                                                                                
      Action:                                                                                                                                                                                                      
        - "dynamodb:DescribeStream"                                                                                                                                                                                
        - "dynamodb:GetRecords"                                                                                                                                                                                    
        - "dynamodb:GetShardIterator"                                                                                                                                                                              
        - "dynamodb:ListStreams"                                                                                                                                                                                   
        - "dynamodb:UpdateItem"                                                                                                                                                                                    
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_MATCH_SCORES_TABLE_NAME}"                                                                       
                                                                                                                                                                                                                   
  environment:                                                                                                                                                                                                     
    DB_HOST: ${file(./env.yml):DB_HOST.${opt:stage, self:provider.stage}}                                                                                                                                          
    DYNAMODB_MATCH_SCORES_TABLE_NAME: match-scores-${opt:stage, self:provider.stage}                                                                                                                               
                                                                                                                                                                                                                   
plugins:                                                                                                                                                                                                           
  - serverless-python-requirements                                                                                                                                                                                 
                                                                                                                                                                                                                   
custom:                                                                                                                                                                                                            
  pythonRequirements:                                                                                                                                                                                              
    zip: true                                                                                                                                                                                                      
                                                                                                                                                                                                                   
package:                                                                                                                                                                                                           
  exclude:                                                                                                                                                                                                         
    - .git/                                                                                                                                                                                                        
    - venv/                                                                                                                                                                                                        
    - event.json                                                                                                                                                                                                   
  include:                                                                                                                                                                                                         
    - requirements.txt                                                                                                                                                                                             
    - modules/                                                                                                                                                                                                     
    - src/                                                                                                                                                                                                         
                                                                                                                                                                                                                   
functions:                                                                                                                                                                                                         
  calculate-match-score:                                                                                                                                                                                           
    handler: handler.handler                                                                                                                                                                                       
    name: calculate-match-score-${opt:stage, self:provider.stage}                                                                                                                                                  
    events:                                                                                                                                                                                                        
      - stream:                                                                                                                                                                                                    
          arn: <redacted ARN>                                                                                              
          batchSize: 5                                                                                                                                                                                             
    tags:                                                                                                                                                                                                          
      process: match-scores
```
